apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-db
      tier: backenddb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: yelb-db
        tier: backenddb
    spec:
      containers:
      - name: yelb-db
        image: mreferre/yelb-db:0.6
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        - name: run-postgresql
          mountPath: /var/run/postgresql
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yelb-db-secret
              key: POSTGRES_PASSWORD
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: yelb-db-pvc
      - name: run-postgresql
        emptyDir: {}
      - name: tmp
        emptyDir: {}
