apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
      tier: cache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server
        image: redis:4.0.2
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "125m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
